### ISSUE TITLE
Feature Request: Long-lived connections Support

### ISSUE THREAD

**Issue by HereOrCode** [vocably/hermes#3]
Hi,

This library is excellent; using it has greatly improved the efficiency of developing.

Is there any plan support for long-lived connections?

Some scenarios require the use of long-lived connections.

---

https://developer.chrome.com/docs/extensions/develop/concepts/messaging#connect

```javascript
// content-script.js:

var port = chrome.runtime.connect({name: "knockknock"});
port.postMessage({joke: "Knock knock"});
port.onMessage.addListener(function(msg) {
  if (msg.question === "Who's there?")
    port.postMessage({answer: "Madame"});
  else if (msg.question === "Madame who?")
    port.postMessage({answer: "Madame... Bovary"});
});

// background.js
chrome.runtime.onConnect.addListener(function(port) {
  console.assert(port.name === "knockknock");
  port.onMessage.addListener(function(msg) {
    if (msg.joke === "Knock knock")
      port.postMessage({question: "Who's there?"});
    else if (msg.answer === "Madame")
      port.postMessage({question: "Madame who?"});
    else if (msg.answer === "Madame... Bovary")
      port.postMessage({question: "I don't get it."});
  });
});
```

**Comment by sneas** [comment]
Hey mate, thank you for your kind words. I'm glad that this library is helping not only me but also others.

I created it to scratch my itch. I have never needed long-lived connections. But I love TS and type-safety, so adding this functionality will be a lovely exercise 😋

I can't promise to add it quickly because I'm on vacation right now, but I'll try to dedicate some time to it in the upcoming weeks.

Thanks for starring this lib ❤️
